language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install coveralls
  - pip install -r test-requirements.txt
script:
  - flake8
  - pytest --ignore=server.py --cov=modron
after_success: coveralls
before_install:
  - export TEST_CRED_DIR=./modron/services/tests/creds
  - openssl aes-256-cbc -K $encrypted_e14e3c23c644_key -iv $encrypted_e14e3c23c644_iv
    -in $TEST_CRED_DIR/gdrive/sertoken.pickle.enc -out $TEST_CRED_DIR/gdrive/token.pickle -d
