language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install coveralls
  - pip install -r test-requirements.txt
script:
  - flake8
  - pytest --with-coverage --cover-package=modron
after_success: coveralls
