language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt --upgrade
  - pip install -e .
  - pip install coveralls
  - pip install -r test-requirements.txt
  - pip list
script:
  - flake8
  - pytest --ignore=server.py --cov=modron
after_success: coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_e14e3c23c644_key -iv $encrypted_e14e3c23c644_iv
    -in creds/gdrive/token.pickle.enc -out creds/gdrive/token.pickle -d
