name: playbypost
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.*
  - flask==1.1.*
  - scipy==1.5.*
  - pandas==1.1.*
  - pyyaml
  - humanize
  - pytest-flask
  - pytest
  - pip
  - pip:
      - -e .
      - slackclient
      - slackeventsapi
      - discord.py
