name: playbypost
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.6.*
  - flask==1.1.*
  - pyyaml
  - humanize
  - pytest-flask
  - pytest
  - pip
  - pip:
      - -e .
      - slackclient
      - slackeventsapi
