team_options:
  853806073906593832:
    name: kaluth
    watch_channels:
      - ic_all
      - adrianna_gm
      - adrianna_mezu
      - mezu_hubryr
      - hubryr_gm
    dice_tracked_categories: [853806638346534962]
    reminders: True
    private_channels:
      862094786956886035: bot_testing
    backup_channels:
      - 853806638346534962