name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Store GDrive credentials
      env:
        GDRIVE_B64: ${{ secrets.GDRIVE_B64 }}
      run: |
        echo $GDRIVE_B64 | base64 --decode > ./creds/gdrive/token.pickle
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        pytest
